---

resources:
- name: my-git-repository
  type: git
  source:
    uri: yourditrepository.git
    branch: master

jobs:
- name: hello-world
  plan:
  - get: my-git-repository
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: getourneau/alpine-bash-git}
      inputs:
      - name: my-git-repository
      run:
        path: bash
        args:
        - -c
        - |
           cat my-git-repository/day-1/hello-concourse/test
