#!/bin/bash -eu

source "$(dirname $BASH_SOURCE)"/om-cmd

om_cmd curl -s -p /api/v0/deployed/director/manifest > director_manifest.json

BOSH_CLIENT="ops_manager"
BOSH_CLIENT_SECRET=$(jq -r '.jobs[] | select(.name == "bosh") | .properties.uaa.clients.ops_manager.secret' director_manifest.json)
BOSH_ENVIRONMENT=$(jq -r '.jobs[] | select(.name == "bosh") | .properties.director.address' director_manifest.json)

BOSH_CA_CERT="${PWD}/bosh.crt"
jq -r '.jobs[] | select(.name == "bosh") | .properties.director.config_server.ca_cert' director_manifest.json > "${BOSH_CA_CERT}"


# Get CF deployment guid
om_cmd curl -p /api/v0/deployed/products > deployed_products.json
ERT_DEPLOYMENT_NAME=$(jq -r '.[] | select( .type | contains("cf")) | .guid' "deployed_products.json")

export BOSH_CLIENT
export BOSH_CLIENT_SECRET
export BOSH_CA_CERT
export BOSH_ENVIRONMENT
export ERT_DEPLOYMENT_NAME
